require 'path'

task :default do
  run('test_files/four.txt')
end

task :four do
  run('test_files/four.txt')
end

task :six do
  run('test_files/six.txt')
end

task :eight do
  run('test_files/eight.txt')
end

task :ten do
  run('test_files/ten.txt')
end

task :twelve do
  run('test_files/twelve.txt')
end

task :thirty do
  run('test_files/thirty.txt')
end

task :onehundred do
  run('test_files/onehundred.txt')
end

task :threehundred do
  run('test_files/threehundred.txt')
end

def run(file, num_iterations = 10, num_ants = 2)
  num_ants = ENV['ants'].to_i unless ENV['ants'].nil?
  num_iterations = ENV['iterations'].to_i unless ENV['iterations'].nil?

  path = Path.new(file, num_iterations, num_ants)
  path.search
end
