require 'path'

task :default do
  run('four.txt')
end

task :four do
  run('four.txt', ENV['num_ants'].to_i, ENV['iterations'].to_i)
end

task :six do
  run('six.txt', ENV['num_ants'].to_i, ENV['iterations'].to_i)
end

task :eight do
  run('eight.txt', ENV['num_ants'].to_i, ENV['iterations'].to_i)
end

task :twelve do
  run('twelve.txt', ENV['num_ants'].to_i, ENV['iterations'].to_i)
end

task :ten do
  run('ten.txt', ENV['num_ants'].to_i, ENV['iterations'].to_i)
end

task :thirty do
  run('thirty.txt', ENV['num_ants'].to_i, ENV['iterations'].to_i)
end

task :onehundred do
  run('onehundred.txt', ENV['num_ants'].to_i, ENV['iterations'].to_i)
end

task :threehundred do
  run('threehundred.txt', ENV['num_ants'].to_i, ENV['iterations'].to_i)
end

def run(file, num_iterations = 10, num_ants = 2)
  path = Path.new(file, num_iterations, num_ants)
  path.search
end
