num_units: 50
num_walls: 20

mark_rules:
  1:
    - :attack_opponent
  2:
    - :move_right
    - :move_down
    - :move_up
    - :move_left

david_rules:
  1:
    - :attack_opponent
  2:
    - :move_towards_teammate
  3:
    - :move_right
    - :move_down
    - :move_up
    - :move_left

wall_rules:
  -
