num_david: 30
num_mark: 30
num_walls: 0
vision: 35
damage: 5
attack_distance: 2

mark_rules:
  1:
    - :attack_opponent
  8:
    - :move_down
    - :move_left
    - :move_up
    - :move_right

david_rules:
  1:
    - :attack_opponent
  3:
    - :move_towards_enemy
  4:
    - :move_towards_teammate
  8:
    - :move_down
    - :move_right
    - :move_up
    - :move_left

wall_rules:
  -
