num_units: 40
num_walls: 40
vision: 3
damage: 5

mark_rules:
  1:
    - :attack_opponent
  2:
    - :move_towards_enemy
  8:
    - :move_down
    - :move_left
    - :move_up
    - :move_right

david_rules:
  1:
    - :attack_opponent
  3:
    - :move_towards_enemy
  4:
    - :move_towards_teammate
  8:
    - :move_down
    - :move_right
    - :move_up
    - :move_left

wall_rules:
  -
