num_units: 40
num_walls: 0
vision: 5

mark_rules:
  1:
    - :attack_opponent
  4:
    - :move_down
    - :move_up
    - :move_left
    - :move_right

david_rules:
  1:
    - :attack_opponent
  2:
    - :move_towards_enemy
  3:
    - :move_towards_teammate
  4:
    - :move_down
    - :move_up
    - :move_left
    - :move_right

wall_rules:
  -
