num_units: 30
num_walls: 10

mark_rules:
  1:
    - :attack_opponent
  2:
    - :move_down
    - :move_up
    - :move_left
    - :move_right

david_rules:
  1:
    - :attack_opponent
  2:
    - :move_towards_teammate
  3:
    - :move_down
    - :move_up
    - :move_left
    - :move_right

wall_rules:
  -
