num_units: 20
num_walls: 20

mark_rules:
  1:
    - :attack_opponent
  2:
    - :move_right
    - :move_left
    - :move_up
    - :move_down

david_rules:
  1:
    - :attack_opponent
  2:
    - :move_towards_teammate
    - :move_right
    - :move_left
    - :move_up
    - :move_down

wall_rules:
  -
